Ensure we are not exhausting the sqlalchemy pool
Because of eventlet, notification messages can be consumed more quickly
that than they are wroted to the database, this have to effect to exhaust
the sqlalchemy connection pool and raise:

TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection
timed out, timeout 30

The patch creates a eventlet pool to ensure that the pool never exhausts
and prints a warning message in the log to inform that perhaps the pool
size need to be increased.

Fixes bug #1243251

Change-Id: I5ccdc141c441db32fab361783a31a96015516878