Fixed tox -egenconfig Error
tox -egenconfig Error:
AttributeError: 'module' object has no attribute 'base'
Caused by the ceilometer/agent/base.py removed

Closes-Bug: #1496684

Change-Id: I3d7f569397532b3e6f550e88b7a779567e83fca3