Remove queue declaration and fix lower-constraints jobs
This commit combines the following changes:

* Remove lingering queue declaration from .zuul.yaml file.

    https://review.opendev.org/859777 (master)
    Co-authored-by: Matthias Runge <mrunge@redhat.com>

* Bump up "lxml" to 4.2.3

    While building 'lxml.etree' extension, lower-constraint job
    fails with the error:
    ```
    src/lxml/lxml.etree.c: In function ‘__Pyx_ExceptionSave’:
    src/lxml/lxml.etree.c:202693:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
    202693 |     *type = tstate->exc_type;
           |                     ^~~~~~~~
           |                     curexc_type
    ```

    https://review.opendev.org/744612 (master)
    Co-authored-by: Ghanshyam Mann <gmann@ghanshyammann.com>

* Set upper constraint for cryptography

    Lower constraint job fails due to missing flag
    "X509_V_FLAG_CB_ISSUER_CHECK" while running unit test cases
    ```
    AttributeError: module \'lib\' has no attribute \'ERR_load_RAND_strings\'
    ```
    ERR_load_RAND_strings was removed in cryptography 35.0.0[1]
    Since ceilometer doesn't have a constraint for it, the latest
    package gets installed, which is 38.0.4 as of now.
    This change sets cryptography to use "3.4.8" which is the last
    release to have the missing attribute.

    Co-authored-by: Yadnesh Kulkarni <ykulkarn@redhat.com>

* Bump up "tenacity" to 4.12.0

    Since "async" became a keyword in Python3.7[2], lower constraint
    job fails with error:
    ```
    from tenacity.async import AsyncRetrying
                  ^
    SyntaxError: invalid syntax
    ```

    https://review.opendev.org/744612 (master)
    Co-authored-by: Ghanshyam Mann <gmann@ghanshyammann.com>

* Bump up "oslo.messaging" to 8.0.0

    Since "async" became a keyword in Python3.7[2], lower constraint
    job fails with error:
    ```
    sender = zmq_senders.RequestSenderDirect(conf, async=True)
                                                   ^
    SyntaxError: invalid syntax
    ```
    The use of "async" was changed to "use_async" in [3]

    https://review.opendev.org/744612 (master)
    Co-authored-by: Ghanshyam Mann <gmann@ghanshyammann.com>

[1] https://github.com/pyca/cryptography/commit/c2e97f9a777d9984608240d923f12acd7758f0aa
[2] https://bugs.python.org/issue30406
[3] https://github.com/openstack/oslo.messaging/commit/5626782fac8e0c16e52146040fcf4053aee2c95e

Change-Id: I9b34ac062d45b2b839dc9d6e0cdce696185890e4
(cherry picked from commit 7e545b0fd9fd4a393d9e2af30f9fc370b20078c0)
(cherry picked from commit 142cb0b6e6f6fa85634c5176c84ab15d6511fa89)