[ocata only] Fix alembic requirement
Ceilometer has chosen to not consume upper-constraints.txt, and latest
version of alembic (1.1.0) requires SQLAlchemy 1.1.0, which is
constrained in requirements.txt
This causes error when running py27 tests:

CommandError: SQLAlchemy 1.1.0 or greater is required.

Change-Id: Ie422738b724d1c75779e52f85218fe2c8a4b4243