Fix TypeError from old-style publish_counter calls
Fix calls to publish_counter() that didn't specify the source
explicitly, to avoid the following error since the function
signature has changed:

  TypeError: publish_counter() takes exactly 5 arguments (4 given)

Change-Id: Ief05842be7b9c815a60827f6356f9064fef8182c
Signed-off-by: Doug Hellmann <doug.hellmann@dreamhost.com>