Remove queue declaration and fix lower-constraints, docs jobs
This commit combines the following changes:

* Remove lingering queue declaration from .zuul.yaml file

    https://review.opendev.org/859777 (master)
    Co-authored-by: Matthias Runge <mrunge@redhat.com>

* Set upper constraint for cryptography

    Lower constraint job fails due to missing flag
    "X509_V_FLAG_CB_ISSUER_CHECK" while running unit test cases
    ```
    AttributeError: module \'lib\' has no attribute \'ERR_load_RAND_strings\'
    ```
    ERR_load_RAND_strings was removed in cryptography 35.0.0[1]
    Since ceilometer doesn't have a constraint for it, the latest
    package gets installed, which is 38.0.4 as of now.
    This change sets cryptography to use "3.4.8" which is the last
    release to have the missing attribute.

    Co-authored-by: Yadnesh Kulkarni <ykulkarn@redhat.com>

* Replace oslo_utils.fnmatch with fnmatch

    The oslo_utils.fnmatch module was added to solve an issue in py2.7
    but it is no longer required because py2.7 is no longer supported.
    The module was deprecated since oslo.utils 4.9.1[2] and the stdlib's
    fnmatch module should be used instead.

    https://review.opendev.org/799654 (master)
    https://review.opendev.org/855557 (stable/victoria)
    Co-authored-by: Takashi Kajinami <tkajinam@redhat.com>

* Bumpup msgpack version from 0.5.0 to 0.5.2

    In msgpack==0.5.0 keyword argument "raw" is not available due to
    which lower-constraint job fails with error:
    ```
    TypeError: unpackb() got an unexpected keyword argument 'raw'
    ```

    https://review.opendev.org/766930 (master)
    Co-authored-by: Matthias Runge <mrunge@redhat.com>

[1] https://github.com/pyca/cryptography/commit/c2e97f9a777d9984608240d923f12acd7758f0aa
[2] 4c893c92f551c9dd2a7cfbe7ae8171ad8139df0b

Change-Id: I9b34ac062d45b2b839dc9d6e0cdce696185890e4
(cherry picked from commit 7e545b0fd9fd4a393d9e2af30f9fc370b20078c0)
(cherry picked from commit 142cb0b6e6f6fa85634c5176c84ab15d6511fa89)
(cherry picked from commit 482e1e974f6773160cc5ab62dd5c6143d0c40568)