[stable-only] Cap msgpack
periodic job py27 started to fail with:
TypeError: __init__() got an unexpected keyword argument 'encoding'

This failure comes with the new version of msgpack (1.0.0).

Since ceilometer does not use global upper-constraints.txt from
requirements repository, msgpack has to be constrained in
requirements.txt

Change-Id: I3ca76c80b96d49d4d256110c8fca13f9365add0d
(cherry picked from commit f63a65acc0b70699e366f2ffe9f449835020e107)
(cherry picked from commit 9923f27d24ef91f8600f428546df035214f6ec15)