Remove queue declaration and fix lower-constraint job
This commit combines 2 changes:

* Remove lingering queue declaration from .zuul.yaml file

* Set upper constraint for cryptography

Lower constraint job fails due to missing flag
"X509_V_FLAG_CB_ISSUER_CHECK" while running unit test cases
```
AttributeError: module \'lib\' has no attribute \'X509_V_FLAG_CB_ISSUER_CHECK\'
```

This flag was deprecated in cryptography 37.0.0 [1]

Since ceilometer doesn't have a constraint for it, the latest package
gets installed, which is 38.0.4 as of now.

This change sets cryptography to use "36.0.2" which is the last release
to have the missing x509 flag.

[1] https://github.com/pyca/cryptography/commit/03f96199a59dff30c388142e4fbac1fc3c475041

Change-Id: I9b34ac062d45b2b839dc9d6e0cdce696185890e4
(cherry picked from commit 7e545b0fd9fd4a393d9e2af30f9fc370b20078c0)
(cherry picked from commit 142cb0b6e6f6fa85634c5176c84ab15d6511fa89)