[stable-only] Fix sphinx requirement
Sphinx 2.0.0 dropped python 2.7 and 3.4 support.
Ceilometer use global upper-constraints.txt only from Train, before
that there isn't any upper constraint for the packages and job
openstack-tox-py27 tries to install Sphinx 2.0.1 and fails [1] with:

 Downloading http://mirror.dfw.rax.openstack.org/wheel/ubuntu-16.04-x86_64/sphinx/Sphinx-2.0.1-py2.py3-none-any.whl (3.2MB)
 ERROR: Sphinx requires Python '>=3.5' but the running Python is 2.7.12

 Conflicts:
	test-requirements.txt

Note(elod.illes): conflict caused by not having patch
I9e8b79d7a18cd36946daff10abb1a2f43b1aa3a1 in stable/queens.

[1] http://logs.openstack.org/periodic-stable/opendev.org/openstack/ceilometer/stable/rocky/openstack-tox-py27/b47132e/job-output.txt.gz#_2019-05-10_06_26_02_016271

Change-Id: I4ad330dce974236be90259cd6e9f48585ff44816
(cherry picked from commit e47d366fbba74150e1e39785bb1f4a7a5d2011ea)